### ISSUE TITLE
bosh-lite command

### ISSUE THREAD

**Issue by michaelgrifalconi** [cloudfoundry-community/logsearch-boshworkspace#11]
From the readme:

```
bosh prepare deployment
```

is not a valid bosh-lite command

**Comment by rkoster** [comment]
Have you tried using `bundle exec bosh prepare deployment`

**Comment by shinji62** [comment]
bosh-lite as nothing to do with bosh, `bosh prepare` come from https://github.com/cloudfoundry-incubator/bosh-workspace.

Are you sure you did  `bundle install` before ?

**Comment by michaelgrifalconi** [comment]
Thanks for your help, maybe I am missing something:

I have a running bosh-lite VM with vagrant, and I am able to deploy CF, Losearch Boshrelease and so on.
These are my steps:

I deleted the old deployments, created another folder and cloned this repo.
Executed `bundle install` (got some errors, installed cmake and pkg-config and did it again, this time with success).
`bosh deployment logsearch-warden`
`bundle exec bosh prepare deployment` (as bosh prepare deployment gives me this error:"Unknown command: prepare deployment")

And I get this:

```

Failed to load plugin /home/user/.bundler/ruby/1.9.1/bosh-workspace-4e49de6b1d42/lib/bosh/cli/commands/deployment_patch.rb: /home/user/.bundler/ruby/1.9.1/bosh-workspace-4e49de6b1d42/lib/bosh/workspace/helpers/git_credentials_helper.rb:76: unknown type of %string
      when %i(private_key)
              ^
/home/user/.bundler/ruby/1.9.1/bosh-workspace-4e49de6b1d42/lib/bosh/workspace/helpers/git_credentials_helper.rb:76: syntax error, unexpected $end
      when %i(private_key)
              ^

```

**Comment by rkoster** [comment]
@tyyko which version of ruby are you using?

**Comment by michaelgrifalconi** [comment]
```
 ruby -v
ruby 1.9.3p484 (2013-11-22 revision 43786) [x86_64-linux]
```

the default version installed by
 `sudo apt-get install –y build-essential ruby ruby-dev libxml2-dev libsqlite3-dev libxslt1-dev libpq-dev libmysqlclient-dev` 
to use the bosh CLI

**Comment by drnic** [comment]
This command is a bosh cli plugin from bosh-workspace rubygem.

Either via bundler:

bundle install

bundle exec bosh prepare workspace

Or via rubygems 

gem install bosh-workspace 

bosh prepare workspace

BTW ruby 1.9.3 is no longer a supported ruby version by ruby-core team and is also no longer being actively tested against by CF/BOSH teams I think.

**Comment by shinji62** [comment]
Yes CF team is moving to 2.1.4.

**Comment by michaelgrifalconi** [comment]
Hello, thanks for your help.

I installed ruby 2.0.0-p643 (as on .ruby-version on this project asks for 2.0.0)
Edited .ruby-version to 2.0.0-p643
`gem install bosh-workspace` with success
`bosh prepare workspace` unknown command workspace
`bundle install` with success
`bosh deployment logsearch-warden
bosh prepare deployment` with this error:

```

Cloning release 'logsearch' to satisfy template references
/home/mich/.rbenv/versions/2.0.0-p643/lib/ruby/gems/2.0.0/gems/git-1.2.9.1/lib/git/lib.rb:917:in `command': git '--git-dir=/home/mich/logsearch-boshworkspace/.releases/logsearch/.git' '--work-tree=/home/mich/logsearch-boshworkspace/.releases/logsearch' log '-30' '--no-color' '--pretty=raw' 'releases/logsearch-18.yml'  2>&1:fatal: ambiguous argument 'releases/logsearch-18.yml': unknown revision or path not in the working tree. (Git::GitExecuteError)
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
        from /home/mich/.rbenv/versions/2.0.0-p643/lib/ruby/gems/2.0.0/gems/git-1.2.9.1/lib/git/lib.rb:846:in `command_lines'
        from /home/mich/.rbenv/versions/2.0.0-p643/lib/ruby/gems/2.0.0/gems/git-1.2.9.1/lib/git/lib.rb:145:in `full_log_commits'
        from /home/mich/.rbenv/versions/2.0.0-p643/lib/ruby/gems/2.0.0/gems/git-1.2.9.1/lib/git/log.rb:119:in `run_log'
        from /home/mich/.rbenv/versions/2.0.0-p643/lib/ruby/gems/2.0.0/gems/git-1.2.9.1/lib/git/log.rb:112:in `check_log'
        from /home/mich/.rbenv/versions/2.0.0-p643/lib/ruby/gems/2.0.0/gems/git-1.2.9.1/lib/git/log.rb:89:in `first'
        from /home/mich/.rbenv/versions/2.0.0-p643/lib/ruby/gems/2.0.0/gems/bosh-workspace-0.8.5/lib/bosh/workspace/release.rb:59:in `version_ref'
        from /home/mich/.rbenv/versions/2.0.0-p643/lib/ruby/gems/2.0.0/gems/bosh-workspace-0.8.5/lib/bosh/workspace/release.rb:18:in `update_repo'
        from /home/mich/.rbenv/versions/2.0.0-p643/lib/ruby/gems/2.0.0/gems/bosh-workspace-0.8.5/lib/bosh/cli/commands/prepare.rb:29:in `block in prepare_release_repos'
        from /home/mich/.rbenv/versions/2.0.0-p643/lib/ruby/gems/2.0.0/gems/bosh-workspace-0.8.5/lib/bosh/cli/commands/prepare.rb:27:in `each'
        from /home/mich/.rbenv/versions/2.0.0-p643/lib/ruby/gems/2.0.0/gems/bosh-workspace-0.8.5/lib/bosh/cli/commands/prepare.rb:27:in `prepare_release_repos'
        from /home/mich/.rbenv/versions/2.0.0-p643/lib/ruby/gems/2.0.0/gems/bosh-workspace-0.8.5/lib/bosh/cli/commands/prepare.rb:17:in `prepare'
        from /home/mich/.rbenv/versions/2.0.0-p643/lib/ruby/gems/2.0.0/gems/bosh_cli-1.2881.0/lib/cli/command_handler.rb:57:in `run'
        from /home/mich/.rbenv/versions/2.0.0-p643/lib/ruby/gems/2.0.0/gems/bosh_cli-1.2881.0/lib/cli/runner.rb:56:in `run'
        from /home/mich/.rbenv/versions/2.0.0-p643/lib/ruby/gems/2.0.0/gems/bosh_cli-1.2881.0/bin/bosh:16:in `<top (required)>'
        from /home/mich/.rbenv/versions/2.0.0-p643/bin/bosh:23:in `load'
        from /home/mich/.rbenv/versions/2.0.0-p643/bin/bosh:23:in `<main>'
```

If I use `bundle exec bosh prepare deployment` I get:

```
Authentication is required for: https://github.com/logsearch/logsearch-boshrelease.git
Credentials file does not exist: /home/mich/logsearch-boshworkspace/.credentials.yml
```

I am behind a proxy so I need to use this format to use git:
`git clone https://address/`

 Thank you!

**Comment by rkoster** [comment]
Yhea I still have to figure out a better way of check for authentication. Currently it will raise the above error when the connection fails for some reason. I found that [`check_connection`](https://github.com/cloudfoundry-incubator/bosh-workspace/blob/master/lib/bosh/workspace/helpers/git_credentials_helper.rb#L34) will also return false if libgit2 has been compiled without support for `https` or `ssh`.
Could you try uninstalling rugged (`gem uninstall rugged`), and then before installing it again (`bundle install`), install the [optional libgit2 dependencies](https://github.com/libgit2/libgit2#optional-dependencies).

**Comment by michaelgrifalconi** [comment]
```
gem uninstall rugged
sudo apt-get install libpthread-stubs0-dev
sudo apt-get install libssh2-php
sudo apt-get install openssl
bundle install
bosh deployment logsearch-warden
```

`bosh prepare deployment` same error as before 
`bundle exec bosh prepare deployment` same error as before
I hope I did not misunderstood the right packages of the dependencies

**Comment by rkoster** [comment]
According to [stackoverflow](http://serverfault.com/questions/249340/install-openssl-dev-on-ubuntu-server) you will need `apt-get install libssl-dev`.

**Comment by michaelgrifalconi** [comment]
Was already installed :( 
`0 upgraded, 0 newly installed, 0 to remove and 8 not upgraded.`
The system was set up some days ago so it's not so old, I can upgrade all if you think can be useful

**Comment by rkoster** [comment]
Can you edit:

```
`bundle show bosh-workspace`/lib/bosh/workspace/helpers/git_credentials_helper.rb
```

and comment out [these lines](https://github.com/cloudfoundry-incubator/bosh-workspace/blob/master/lib/bosh/workspace/helpers/git_credentials_helper.rb#L26-L29) (ruby uses # for comments). Hopefully this will reveal the underlying issue.

**Comment by michaelgrifalconi** [comment]
`bash: /var/lib/gems/1.9.1/bundler/gems/bosh-workspace-4e49de6b1d42/lib/bosh/workspace/helpers/git_credentials_helper.rb: Permission denied
` with my user, and also with root
(dont ask me about 1.9.1, I installed 2.0 and `ruby -v` gives me `ruby 2.0.0`

**Comment by rkoster** [comment]
Sorry I don't understand what you did. Did you get permission denied while trying to edit a file as root?
