### ISSUE TITLE
Error running  rake plugins:update

### ISSUE THREAD

**Issue by dcallao** [cloudfoundry-community/logsearch-boshworkspace#7]
I get this error running rake plugins:update:

dcallao@ip-10-202-86-106:/data/workspace/logsearch$ sudo rake plugins:update
sudo: unable to resolve host ip-10-202-86-106
rake aborted!
Don't know how to build task 'plugins:update'

(See full trace by running task with --trace)

**Comment by rkoster** [comment]
cc @drnic

**Comment by rkoster** [comment]
Was this issue related to https://github.com/cloudfoundry-community/logsearch-boshworkspace/pull/8?

**Comment by drnic** [comment]
I think the issue here was cloning the wrong repo/branch. Can be closed.
